Migrate to .net 5 / 6 / Optimizely + localization
Geta/Geta.EPi.HotspotsEditor pull request #13
Opened 2022-06-15 08:00 UTC by ellinge

![image](https://user-images.githubusercontent.com/17863113/173773953-f95224b0-7c49-47ca-b04a-a0a30ccfe74a.png)

A basic migration to .net 5 / 6 with localization added. Seems to be working but don't have any experience with the product from previous versions so not sure. 

Perhaps one should change it to be non commerce specific to be able to specify roots with an attribute and be aware of AllowedTypes.

2022-06-15 13:15 UTC, ellinge commented
Removed the dependency on Commerce and added the possibility to specify allowed types and roots for selecting other stuff. Fixing #9 
```
    [Roots(RootSelection.StartPage | RootSelection.CommerceRootPage)]
    [Types(typeof(PageData), typeof(ProductContent))]
```
![image](https://user-images.githubusercontent.com/17863113/173836000-c8a02664-5abf-4b8c-8e54-94d850e21bbb.png)

2022-06-17 08:21 UTC, marisks commented
We definitely need a new repository.

2022-06-17 08:28 UTC, marisks requested changes

2022-06-17 08:28 UTC, marisks commented on .gitignore
> -## Ignore Visual Studio temporary files, build results, and
This gitignore doesn't look standard one. Should we update to a common gitignore and add project-specific things at the end?

2022-06-17 08:28 UTC, marisks commented on src/Geta.Optimizely.HotspotsEditor/Geta.Optimizely.HotspotsEditor.csproj
> +    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
Just use net6.0 and the first Optimizely version that supports it.

P.S. Old Optimizely versions have some security holes, so better force upgrade for everyone. Also, net5 is dead - no need to support it.

2022-06-17 08:28 UTC, marisks commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
Let's use common conventions - packaging the same way as in other of our projects.

2022-06-17 11:21 UTC, ellinge commented on .gitignore
> -## Ignore Visual Studio temporary files, build results, and
I think I based it upon one of your other projects:
https://github.com/Geta/geta-optimizely-genericlinks/blob/master/.gitignore

2022-06-17 11:22 UTC, ellinge commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
I based it upon one of your other projects:
https://github.com/Geta/geta-optimizely-genericlinks/blob/master/src/pack.proj

2022-06-17 11:27 UTC, ellinge commented
> We definitely need a new repository.

A rename was suggested in #10

2022-06-17 15:18 UTC, ellinge commented on .gitignore
> -## Ignore Visual Studio temporary files, build results, and
Changed it to be based upoon https://github.com/Geta/geta-notfoundhandler/blob/master/.gitignore instead

2022-06-17 15:39 UTC, ellinge commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
Tried to check https://github.com/Geta/geta-notfoundhandler for inspiration, the reason for the pack.proj seems to be handle module zip (ClientResources) which notfoundhandler lacks.

2022-06-17 19:52 UTC, marisks commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
Sitemaps is a better example: https://github.com/Geta/geta-optimizely-sitemaps

2022-06-17 19:54 UTC, marisks commented
> > We definitely need a new repository.
> 
> A rename was suggested in #10

Rename is not an option. We need a separate repository. But after migration is done in this PR, we will create a repo and will move the new code there.

2022-06-17 20:02 UTC, ellinge commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
https://github.com/Geta/geta-optimizely-sitemaps/blob/master/src/Geta.Optimizely.Sitemaps/msbuild/Main.proj so you want it here instead?

2022-06-17 20:03 UTC, marisks commented on src/pack.proj
> +<?xml version="1.0" encoding="utf-8"?>
Yes, with this file name and with cleaner csproj.

2022-07-19 06:10 UTC, merged

2022-07-19 10:54 UTC, ellinge commented
History gone bye bye 🙄

2022-07-19 10:56 UTC, marisks commented
Yes, because that is a new package, so new history.
The history for the old package will be here anyways.

2022-07-19 11:26 UTC, ellinge commented
net6 merged into master of new github repo with history kept:
```
git clone https://github.com/Geta/Geta.EPi.HotspotsEditor.git
cd .\Geta.EPi.HotspotsEditor\
git checkout net6
git remote add neworigin https://github.com/ellinge/newtestrep.git
git push -u neworigin net6:master
```